### ISSUE TITLE
サイズ6455

### ISSUE THREAD

**Issue by sawatalyn** [Dolly1016/Nebula-OLD-#9]
こんにちは、あなたのMODは大きなパケット（サイズ6455）を送信しており、すべてのプレーヤーが確実に受信できるわけではありません。送信されるメッセージの最大サイズを1400バイト以下に変更することはできますか？このサイズであれば、誰でも受信できるはずです。もっと質問がある場合は、@miniduikboot に尋ねてください。

**Comment by sawatalyn** [comment]
LogOutput.log:

Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Nebula.Module.ModNewsHistory.<Initialize>g__GetEnumerator|4_0()+MoveNext()
   at Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )


IL2CPP-to-Managed トランポリンで例外が発生し、il2cpp に渡されませんでした: System.UriFormatException: 無効な URI: URI の形式を特定できませんでした。
    System.Uri.CreateThis で (文字列 uri、ブール値の dontEscape、UriKind uriKind、UriCreationOptions & creationOptions)
    System.Uri..ctor (文字列 uriString) で
    Nebula.Module.ModNewsHistory.<Initialize>g__GetEnumerator|4_0()+MoveNext() で
    Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext (IntPtr、Il2CppMethodInfo*) で

**Comment by sawatalyn** [comment]
`[Message: Preloader] BepInEx 6.0.0-be.667 - Among Us
[Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2020.3.22f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [TheNebula 2.2.2]
[Message:   BepInEx] Chainloader startup complete
`

**Comment by sawatalyn** [comment]
player1のLogOutput.log
[Message: Preloader] BepInEx 6.0.0-be.667 - Among Us
[Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2020.3.22f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [TheNebula 2.2.2]
[Message:   BepInEx] Chainloader startup complete

player2のLogOutput.log
[Message: Preloader] BepInEx 6.0.0-be.667 - Among Us
[Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2020.3.22f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [TheNebula 2.2.2]
[Message:   BepInEx] Chainloader startup complete
[Info   :Il2CppInterop] Registered mono type BepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumerator in il2cpp domain
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Nebula.Module.ModNewsHistory.<Initialize>g__GetEnumerator|4_0()+MoveNext()
   at Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
[Info   :Il2CppInterop] Registered mono type Nebula.Components.TextInputField in il2cpp domain

**Comment by Dolly1016** [comment]
Thank you for your reporting.
What language are you using in game?
This URI is generated according to the language setting.

**Comment by sawatalyn** [comment]
We use Chinese language, and the mod is translated by 四个憨批.

**Comment by Dolly1016** [comment]
It looks like a problem where sometimes the uri is not generated successfully.
When was the oversized packet observed?

**Comment by Dolly1016** [comment]
I've heard that someone is making a version for Chinese speakers.
Did you both get it from this repository?

**Comment by sawatalyn** [comment]
uh, i don't know if it is, i just get the game "Nedula V2.2.2" from 四个憨批汉化组, they are commended in the doc here. They supply many chinese translated Among Us mods for us, including this mod.

> I've heard that someone is making a version for Chinese speakers. Did you both get it from this repository?

**Comment by Dolly1016** [comment]
Can you see a screen like this when you start the game?
If you find the difference in the logo, it may be not what you can get here.

![20230321005612](https://user-images.githubusercontent.com/87486443/226397199-1269324a-d96b-490b-b096-e1367210bf4f.png)

**Comment by sawatalyn** [comment]
ok, i'll try to do that. I'll close comment when got a fix method or  result. thanks for help.

> They didn't seem to make any changes to their contact information. It is a further modification from what I made. Please contact 四个憨批汉化组 first.

**Comment by Huier-Huang** [comment]
> player1のLogOutput.log [Message: Preloader] BepInEx 6.0.0-be.667 - Among Us [Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608 [Info : BepInEx] System platform: Windows 10 64-bit [Info : BepInEx] Process bitness: 32-bit (x86) [Info : BepInEx] Running under Unity 2020.3.22f1 [Info : BepInEx] Runtime version: 6.0.7 [Info : BepInEx] Runtime information: .NET 6.0.7 [Info : Preloader] 0 patcher plugins loaded [Info : Preloader] 0 assemblies discovered [Message:AssemblyPatcher] Executing 0 patch(es) [Message: BepInEx] Chainloader initialized [Info :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain [Info : BepInEx] 1 plugin to load [Info : BepInEx] Loading [TheNebula 2.2.2] [Message: BepInEx] Chainloader startup complete
> 
> player2のLogOutput.log [Message: Preloader] BepInEx 6.0.0-be.667 - Among Us [Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608 [Info : BepInEx] System platform: Windows 10 64-bit [Info : BepInEx] Process bitness: 32-bit (x86) [Info : BepInEx] Running under Unity 2020.3.22f1 [Info : BepInEx] Runtime version: 6.0.7 [Info : BepInEx] Runtime information: .NET 6.0.7 [Info : Preloader] 0 patcher plugins loaded [Info : Preloader] 0 assemblies discovered [Message:AssemblyPatcher] Executing 0 patch(es) [Message: BepInEx] Chainloader initialized [Info :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain [Info : BepInEx] 1 plugin to load [Info : BepInEx] Loading [TheNebula 2.2.2] [Message: BepInEx] Chainloader startup complete [Info :Il2CppInterop] Registered mono type BepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumerator in il2cpp domain [Error :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.UriFormatException: Invalid URI: The format of the URI could not be determined. at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) at System.Uri..ctor(String uriString) at Nebula.Module.ModNewsHistory.g__GetEnumerator|4_0()+MoveNext() at Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* ) [Info :Il2CppInterop] Registered mono type Nebula.Components.TextInputField in il2cpp domain

这个报错应该和发送到服务器数据包过大无关

**Comment by sawatalyn** [comment]
> > player1のLogOutput.log [Message: Preloader] BepInEx 6.0.0-be.667 - Among Us [Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608 [Info : BepInEx] System platform: Windows 10 64-bit [Info : BepInEx] Process bitness: 32-bit (x86) [Info : BepInEx] Running under Unity 2020.3.22f1 [Info : BepInEx] Runtime version: 6.0.7 [Info : BepInEx] Runtime information: .NET 6.0.7 [Info : Preloader] 0 patcher plugins loaded [Info : Preloader] 0 assemblies discovered [Message:AssemblyPatcher] Executing 0 patch(es) [Message: BepInEx] Chainloader initialized [Info :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain [Info : BepInEx] 1 plugin to load [Info : BepInEx] Loading [TheNebula 2.2.2] [Message: BepInEx] Chainloader startup complete
> > player2のLogOutput.log [Message: Preloader] BepInEx 6.0.0-be.667 - Among Us [Message: Preloader] Built from commit 6b500b35727716f8ba182dedae304a628dbbb608 [Info : BepInEx] System platform: Windows 10 64-bit [Info : BepInEx] Process bitness: 32-bit (x86) [Info : BepInEx] Running under Unity 2020.3.22f1 [Info : BepInEx] Runtime version: 6.0.7 [Info : BepInEx] Runtime information: .NET 6.0.7 [Info : Preloader] 0 patcher plugins loaded [Info : Preloader] 0 assemblies discovered [Message:AssemblyPatcher] Executing 0 patch(es) [Message: BepInEx] Chainloader initialized [Info :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain [Info : BepInEx] 1 plugin to load [Info : BepInEx] Loading [TheNebula 2.2.2] [Message: BepInEx] Chainloader startup complete [Info :Il2CppInterop] Registered mono type BepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumerator in il2cpp domain [Error :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.UriFormatException: Invalid URI: The format of the URI could not be determined. at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) at System.Uri..ctor(String uriString) at Nebula.Module.ModNewsHistory.g__GetEnumerator|4_0()+MoveNext() at Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* ) [Info :Il2CppInterop] Registered mono type Nebula.Components.TextInputField in il2cpp domain
> 
> 这个报错应该和发送到服务器数据包过大无关

额那应该和什么有关？我该怎么测试这个原因？

**Comment by Dolly1016** [comment]
Thanks. We will make changes to reduce the packet size in the next version.

**Comment by sawatalyn** [comment]
> Thanks. We will make changes to reduce the packet size in the next version.

Ok，thank you for everything.I'll try the new version.
